export const ROUTES = {
  home: "/",
  downloadApp: "/download-app",
  sewakanKos: "/sewakan-kos",
  kos: "/kos",
  singgahsini: "/singgahsini",
  kosAndalan: "/kos-andalan",
  apartemen: "/apartemen",
  jualBeliProperti: "/jual-beli-properti",
  bantuan: "/bantuan",
  syaratKetentuan: "/syarat-ketentuan",
  kebijakanPrivasi: "/kebijakan-privasi",
  blog: "/blog",
  cari: "/cari",
} as const;